### ISSUE TITLE
Take errant characters out of help menu

### ISSUE THREAD

**Issue by jfarbowitz** [amiaopensource/checksumthing#1]
Things like `PRE` and `POST` are showing up in the help menu in between text that we want to display. We need to take them out.

**Comment by joshuatj** [comment]
The PRE and POST are not bugs. It's auto-generated from the _dest_ argument. 

> The value is saved to an attribute of that name on the Namespace object returned when the command line arguments are parsed.

source: https://pymotw.com/2/argparse/
